
[air]
	#Range: > 1
	uses_per_tank = 2000
	#Range: > 1
	uses_per_tank_hover = 3500

[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.01
	#Range: 0.01 ~ 100.0
	vertical = 0.3
	#Range: 0.01 ~ 100.0
	acceleration = 0.045
	#Range: -100.0 ~ 0.0
	hover_descend = 0.0
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8

[enchantments]
	list = []
	is_blacklist = true

